on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          input_dir: './md'
          output_dir: './html'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: List files in the md folder
        run: |
          ls -lR ${{ github.workspace }}/md
      - name: List files in the html folder
        run: |
          ls -lR ${{ github.workspace }}/html
      - run: echo "$(git log -n 1 --pretty=format:%an)"
      - run: echo "$(git log -n 1 --pretty=format:%ae)"
      - name: Commit html
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git commit -am "Automated html"
          git push