on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Markdown to HTML
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          input_dir: './md'
          output_dir: './html'
          template: './tmpl/contentPage.html'
      # Use the output from the `hello` step
      - name: List files in the md folder
        run: |
          ls -lR ${{ github.workspace }}/md
      - name: List files in the html folder
        run: |
          ls -lR ${{ github.workspace }}/html
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./html
      #    publish_branch: gh-pages
      #    allow_empty_commit: true
      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@v4.3.3
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: ./html # The folder the action should deploy.
     
      - name: create and commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "auto-build html" -a
          echo "::set-output name=push::true"
        shell: bash
      
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }} 